// Generated by Vortex3D Compiler
#include "C:/Users/sudol/vortex3d/runtime/vortex_engine.hpp"
using namespace vortex;

// Global Game State
static Engine& eng = Engine::instance();

// --- Global State & Assets ---
static int g_player_id = 0;
static int g_enemies[64];
static int g_enemy_count = 0;
static int g_projectiles[128];
static int g_proj_count = 0;
static float g_score = 0.0f;
static float g_player_health = 100.0f;
static bool g_game_over = false;
static float g_enemy_spawn_timer = 0.0f;
static float g_shoot_cooldown = 0.0f;

void spawn_plasma_bolt(vec3 origin, vec3 dir) {
    if (g_proj_count >= 128) return;
    Material laser_mat;
    laser_mat.albedo = color::cyan();
    int p = eng.spawn_entity("projectile", MeshType::LASER, origin, laser_mat, 0.4f);
    Entity* pe = eng.get_entity(p);
    if (pe) {
        pe->velocity = dir * 45.0f;
        pe->custom_timer = 2.5f; // lifetime
    }
    g_projectiles[g_proj_count++] = p;
    eng.particles.burst(origin, 8, color::cyan(), 4.0f, 0.2f);
    eng.play_sound_fx(1);
}

void spawn_viper_drone(vec3 pos) {
    if (g_enemy_count >= 64) return;
    Material drone_mat;
    drone_mat.albedo = color(1.0f, 0.15f, 0.25f);
    int e = eng.spawn_entity("enemy", MeshType::CUBE, pos, drone_mat, 1.2f);
    Entity* ent = eng.get_entity(e);
    if (ent) {
        ent->health = 50.0f;
        ent->tr.scale = vec3(1.2f, 1.2f, 1.2f);
    }
    g_enemies[g_enemy_count++] = e;
}

void setup_vortex_game() {
    eng.fog_enabled = true;
    eng.fog_color = color(0.04f, 0.05f, 0.09f);
    eng.sun.position = vec3(25, 45, 25);
    eng.ambient_light = color(0.18f, 0.20f, 0.28f);

    Material pillar_mat;
    pillar_mat.albedo = color(0.15f, 0.25f, 0.4f);
    eng.spawn_entity("obstacle", MeshType::PILLAR, vec3(-15, 0, -15), pillar_mat, 1.5f);
    eng.spawn_entity("obstacle", MeshType::PILLAR, vec3( 15, 0, -15), pillar_mat, 1.5f);
    eng.spawn_entity("obstacle", MeshType::PILLAR, vec3(-15, 0,  15), pillar_mat, 1.5f);
    eng.spawn_entity("obstacle", MeshType::PILLAR, vec3( 15, 0,  15), pillar_mat, 1.5f);

    Material p_mat;
    p_mat.albedo = color(0.1f, 0.9f, 0.7f);
    g_player_id = eng.spawn_entity("player", MeshType::CUBE, vec3(0, 1.5f, 0), p_mat, 1.0f);
    Entity* player = eng.get_entity(g_player_id);
    if (player) {
        player->has_rigidbody = true;
        player->use_gravity = true;
    }

    spawn_viper_drone(vec3(-20, 1.2f, -10));
    spawn_viper_drone(vec3( 20, 1.2f, -15));
    spawn_viper_drone(vec3(  0, 1.2f, -25));
}

void on_frame_update(float dt) {
    if (g_game_over) {
        eng.hud.game_over = true;
        if (eng.keys['R']) {
            g_game_over = false;
            g_player_health = 100.0f;
            g_score = 0.0f;
            eng.hud.game_over = false;
            Entity* p = eng.get_entity(g_player_id);
            if (p) { p->tr.position = vec3(0, 1.5f, 0); p->velocity = vec3(0,0,0); }
        }
        return;
    }

    Entity* player = eng.get_entity(g_player_id);
    if (!player) return;

    float move_speed = 14.0f;
    vec3 move_dir(0, 0, 0);
    if (eng.keys['W'] || eng.keys[VK_UP])    move_dir.z -= 1.0f;
    if (eng.keys['S'] || eng.keys[VK_DOWN])  move_dir.z += 1.0f;
    if (eng.keys['A'] || eng.keys[VK_LEFT])  move_dir.x -= 1.0f;
    if (eng.keys['D'] || eng.keys[VK_RIGHT]) move_dir.x += 1.0f;

    if (move_dir.length_sq() > 0.01f) {
        move_dir = move_dir.normalized();
        player->velocity.x = move_dir.x * move_speed;
        player->velocity.z = move_dir.z * move_speed;
        player->tr.rotation.y = std::atan2(-move_dir.x, -move_dir.z) * (180.0f / 3.14159f);
        eng.particles.burst(player->tr.position - vec3(0, 0.5f, 0), 1, color::cyan(), 1.0f, 0.15f);
    } else {
        player->velocity.x *= 0.85f;
        player->velocity.z *= 0.85f;
    }

    if (eng.keys[VK_SPACE] && player->is_grounded) {
        player->velocity.y = 11.0f;
        player->is_grounded = false;
    }

    vec3 cam_offset(0, 7.0f, 13.0f);
    eng.main_camera.position = vec3::lerp(eng.main_camera.position, player->tr.position + cam_offset, 0.12f);
    eng.main_camera.pitch = 24.0f;
    eng.main_camera.yaw = 0.0f;

    if (g_shoot_cooldown > 0.0f) g_shoot_cooldown -= dt;
    if (eng.mouse_left && g_shoot_cooldown <= 0.0f) {
        g_shoot_cooldown = 0.18f;
        vec3 shoot_origin = player->tr.position + vec3(0, 0.5f, 0);
        float rad = player->tr.rotation.y * (3.14159f / 180.0f);
        vec3 fwd(-std::sin(rad), 0, -std::cos(rad));
        if (fwd.length_sq() < 0.01f) fwd = vec3(0, 0, -1);
        spawn_plasma_bolt(shoot_origin, fwd.normalized());
    }

    g_enemy_spawn_timer += dt;
    if (g_enemy_spawn_timer >= 3.0f) {
        g_enemy_spawn_timer = 0.0f;
        float rx = ((rand() % 60) - 30);
        float rz = ((rand() % 60) - 30);
        spawn_viper_drone(vec3(rx, 1.2f, rz));
    }

    for (int i = 0; i < g_enemy_count; ++i) {
        Entity* en = eng.get_entity(g_enemies[i]);
        if (!en || !en->is_alive) continue;
        vec3 to_player = (player->tr.position - en->tr.position);
        float dist = to_player.length();
        if (dist > 1.2f) {
            vec3 dir = to_player.normalized();
            en->tr.position += dir * 4.5f * dt;
            en->tr.rotation.y = std::atan2(-dir.x, -dir.z) * (180.0f / 3.14159f);
        } else {
            g_player_health -= 15.0f * dt;
            eng.play_sound_fx(3);
            if (g_player_health <= 0.0f) {
                g_player_health = 0.0f;
                g_game_over = true;
            }
        }
        en->tr.position.y = 1.2f + 0.3f * std::sin((float)GetTickCount64() * 0.005f + i);
    }

    for (int i = 0; i < g_proj_count; ++i) {
        Entity* pr = eng.get_entity(g_projectiles[i]);
        if (!pr || !pr->is_alive) continue;
        pr->custom_timer -= dt;
        if (pr->custom_timer <= 0.0f) {
            pr->is_alive = false;
        }
    }

    eng.hud.player_health = g_player_health;
    eng.hud.score = (int)g_score;
}

void on_collision_event(Entity& a, Entity& b) {
    Entity* bullet = (a.tag == "projectile") ? &a : ((b.tag == "projectile") ? &b : nullptr);
    Entity* enemy  = (a.tag == "enemy") ? &a : ((b.tag == "enemy") ? &b : nullptr);

    if (bullet && enemy && enemy->is_alive && bullet->is_alive) {
        bullet->is_alive = false;
        enemy->health -= 25.0f;
        eng.particles.burst(enemy->tr.position, 20, color(1.0f, 0.6f, 0.1f), 8.0f, 0.4f);
        if (enemy->health <= 0.0f) {
            enemy->is_alive = false;
            g_score += 100.0f;
            eng.particles.burst(enemy->tr.position, 40, color(1.0f, 0.2f, 0.1f), 12.0f, 0.7f);
            eng.play_sound_fx(2);
        }
    }
}

int WINAPI WinMain(HINSTANCE, HINSTANCE, LPSTR, int) {
    eng.fps_cap = 120.0f;
    eng.init_window("Neon Breach 3D - [Vortex3D Engine]", 1280, 720);
    eng.on_start_fn = setup_vortex_game;
    eng.on_update_fn = on_frame_update;
    eng.on_collision_fn = on_collision_event;
    eng.run();
    return 0;
}
